spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
#  sql:
#    init:
#      platform: mysql
#      schema-locations: classpath:schema-h2.sql
#      data-locations: classpath:data.sql
logging:
  level:
    root: info
